### ISSUE TITLE
Error while running the docker image

### ISSUE THREAD

**Issue by hillsonghimire** [mbasa/pgrServer#6]
which building using the:
`docker-compose build pgrserver`
we get: <i>ERROR: No such service: pgrserver</i>

Then, I checked the docker-compose.yml and tried:
`docker-compose build pgrServer`
we get some exception: <i>pgrServer uses an image, skipping</i>

The issue with
`docker-compose up`

<i>Pulling pgrServer (mbasa/pgrserver:latest)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling pgrServer (mbasa/pgrserver:latest)...
ERROR: pull access denied for mbasa/pgrserver, repository does not exist or may require 'docker login': denied: requested access to the resource is denied</i>

**Comment by nilsnolde** [comment]
yeah, see here for a fix: https://github.com/mbasa/pgrServer/pull/7

**Comment by mbasa** [comment]
Thanks @nilsnolde. Will merge this tomorrow, along with the `develop` branch which has one-way streets support as well as other things. Created a Flutter demo here:  

http://cld06.georepublic.net/pgrserver_demo

which works with Chrome and Firefox, but CORS restriction has to be disabled for Safari.

**Comment by hillsonghimire** [comment]
Thanks @nilsnolde . The issue has been resolved. @mbasa Why is it that its not advised to run with docker image on production server? Is it security or performance issues?

**Comment by mbasa** [comment]
@hillsonghimire performance issues. I personally view Docker containers are suited more for MicroServices instead of full Server applications. PgrServer is fully multi-threaded and requires quite a large amount of memory resources, and unless a Docker container can be allocated to have at least 4 cpu cores and around 16 gb of memory,  I feel PgrServer will be throttled.
